## 📘 Lesson 1: NumPy Basics

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

#Create array
a = np.array([1,2,3,4,5 ])
b = np.array([[1,2],[3,4]])

# Shape and type

print(a.shape)
print(b.shape)
print(b.dtype)

#Basic operations

print(a + 2) #[3,4,5]
print(a * 3) #[3,6,9]
print(a @ a) # Dot product

(5,)
(2, 2)
int64
[3 4 5 6 7]
[ 3  6  9 12 15]
55


### ✅ NumPy Practice Exercise

1. Create a 3×3 matrix with values from 1 to 9
2. Get the mean of each row
3. Multiply the matrix by a scalar
4. Transpose the matrix

In [ ]:
c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

# Mean of each row
print("Row-wise mean:", c.mean(axis=1))

# Multiply the matrix by a scalar
print("Matrix * 2:\n", c * 2)

# Transpose the matrix
print("Transposed matrix:\n", c.T)

Row-wise mean: [2. 5. 8.]
Matrix * 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Transposed matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## 🧠 Lesson: Indexing, Slicing & Reshaping in NumPy

#### **1. Indexing**

In [10]:
import numpy as np

a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]

])

print(a[0, 1]) # Accessing element at row 0, column 1
print(a[2,2]) # 90

20
90


#### **2. Slicing**

In [11]:
# Get the first two row
print(a[:2, :]) # [[10,20,30],[40,50,60]]

# Get the last column
print(a[:, -1]) # [30,60,90]

[[10 20 30]
 [40 50 60]]
[30 60 90]


#### **3. Boolean Masking (Very powerful for filtering)**

In [13]:
# Find elements > 50
print ( a > 50) # [[False,False,False],[False,True,True],[True,True,True]]

#Use the mask to extract values
print(a[a > 50])

[[False False False]
 [False False  True]
 [ True  True  True]]
[60 70 80 90]


#### **4. Reshaping**

In [15]:
b = np.array([1,2,3,4,5,6])
print(b.reshape(2,3)) # 2 rows, 3 columns

# Flatten a matrix back to 1D
c = a.flatten()
print(c) # [10,20,30,40,50,60,70,80,90]

[[1 2 3]
 [4 5 6]]
[10 20 30 40 50 60 70 80 90]


##### 🧪 **Practice Exercise (Try These!):**
1. Create a 4×3 array of numbers from 1 to 12.

2. Extract the second column.

3. Get a submatrix of the last two rows and first two columns.

4. Filter all values greater than 6.

5. Reshape it to a 2×6 matrix and then back to 3×4.

In [ ]:
# Create a 4×3 array of numbers from 1 to 12.

a = np.arange(1, 13).reshape(4, 3)
# or
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10,11,12]
])
# Extract the second column.

print(a[:,1])

# Get a submatrix of the last two rows and first two columns.
print(a[-2:, :2])

# Filter all values greater than 6.
print(a[a > 6])

# Reshape it to a 2×6 matrix and then back to 3×4.

print(a.reshape(2,6))

[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[ 7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
